apiVersion: v1
kind: Service
metadata:
  labels:
    app: amq
  name: cat-tool-activemq
spec:
  ports:
  - name: "61613"
    port: 61613
    targetPort: 61613
  - name: "8161"
    port: 8161
    targetPort: 8161
  selector:
    app: amq
status:
  loadBalancer: {}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: amq
  name: amq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amq
  strategy: {}
  template:
    metadata:
      labels:
        app: amq
    spec:
      containers:
      - name: amq
        image: nltpcontainers.azurecr.io/matecat-activemq:43407
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 61613
        - containerPort: 8161
        resources:
          requests:
            cpu: "10m"
            memory: "330Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
      imagePullSecrets:
        - name: nltp-cr-pull-secret
      restartPolicy: Always
status: {}
