apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: cat-tool-redis
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    app: redis
status:
  loadBalancer: {}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2.7
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - mountPath: /data
          name: redis-data
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "10m"
            memory: "20Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
      restartPolicy: Always
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data-pv-claim
status: {}
