apiVersion: v1
kind: Service
metadata:
  name: clamav
spec:
  ports:
    - protocol: "TCP"
      port: 3310
      targetPort: 3310
  selector:
    app: clamav
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clamav
  template:
    metadata:
      labels:
        app: clamav
    spec:
      containers:
        - name: clamav
          image: clamav/clamav:0.105.1  # TODO
          ports:
            - containerPort: 3310
          resources:
            requests:
              memory: "4G"
              cpu: "1"
            limits:
              memory: "4G"