apiVersion: v1
kind: Service
metadata:
  labels:
    app: docs
  name: docs
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 3000
  selector:
    app: docs
status:
  loadBalancer: {}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docs
  name: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  strategy: {}
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
      - name: docs
        image: nltpcontainers.azurecr.io/nltp-docs:45967
        imagePullPolicy: "IfNotPresent"
        envFrom:
        - configMapRef:
            name: docs-config
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          failureThreshold: 1
          periodSeconds: 60
        startupProbe:
          httpGet:
            path: /
            port: 3000
          failureThreshold: 30
          periodSeconds: 10
        resources:
          requests:
            cpu: "10m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "600Mi"
      imagePullSecrets:
        - name: nltp-cr-pull-secret
      restartPolicy: Always
status: {}