apiVersion: v1
kind: Service
metadata:
  name: file-translation-worker
spec:
  ports:
    - name: http
      protocol: "TCP"
      port: 80
      targetPort: 8080
  selector:
    app: file-translation-worker
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-translation-worker
spec:
  selector:
    matchLabels:
      app: file-translation-worker
  template:
    metadata:
      labels:
        app: file-translation-worker
    spec:
      containers:
        - name: file-translation-worker
          image: nltpcontainers.azurecr.io/file-translation-worker:44545
          imagePullPolicy: "IfNotPresent"
          env:
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: rabbitmq
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: rabbitmq
            - name: RABBITMQ_HOST
              value: $(RABBITMQ_SERVICE_HOST)
            - name: RABBITMQ_PORT
              value: $(RABBITMQ_SERVICE_PORT)
            - name: FILE_TRANSLATION_SERVICE_URL
              value: http://file-translation-service
            - name: FILE_TRANSLATION_SERVICE_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: file-service
            - name: FILE_TRANSLATION_SERVICE_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: file-service
            - name: TRANSLATION_API_SERVICE_URL
              value: http://text-translation-service
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: "10m"
              memory: "200Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
      imagePullSecrets:
        - name: nltp-cr-pull-secret